# The Matrix Exponential

* Reference Notes (5.1 and 5.3)

Solve the system of linear differential equations:

$\dot{x_1} = x_1 + 2 x_2$

$\dot{x_2} = -x_2$

$\dot{\vec{x}} = A\vec{x}$

where: $A = \begin{bmatrix}
0 & -1 \\
1 & 0
\end{bmatrix}, \vec{x} = \begin{bmatrix}x_1\\ x_2 \end{bmatrix}$

We can solve this differential equation using the matrix exponential.

Notice that:

$\vec{x}(t) = e^{At} \vec{x_0}$

is a solution to the differential equation.

$\dot{\vec{x}}(t) = A e^{At} \vec{x_0} = A \vec{x}(t)$



In [1]:
import sympy
sympy.init_printing()
t = sympy.symbols('t', real=True)
A = sympy.Matrix([
    [0, -1],
    [1, 0]
])
A = sympy.Matrix([
    [0, 1],
    [2, -1]
])
sympy.exp(A*t)

⎡    t    -2⋅t     t    -2⋅t ⎤
⎢ 2⋅ℯ    ℯ        ℯ    ℯ     ⎥
⎢ ──── + ─────    ── - ───── ⎥
⎢  3       3      3      3   ⎥
⎢                            ⎥
⎢   t      -2⋅t   t      -2⋅t⎥
⎢2⋅ℯ    2⋅ℯ      ℯ    2⋅ℯ    ⎥
⎢──── - ───────  ── + ───────⎥
⎣ 3        3     3       3   ⎦

In [2]:
evects = sympy.Matrix.eigenvects(A)
evects

⎡⎛       ⎡⎡-1/2⎤⎤⎞  ⎛      ⎡⎡1⎤⎤⎞⎤
⎢⎜-2, 1, ⎢⎢    ⎥⎥⎟, ⎜1, 1, ⎢⎢ ⎥⎥⎟⎥
⎣⎝       ⎣⎣ 1  ⎦⎦⎠  ⎝      ⎣⎣1⎦⎦⎠⎦

We can compute the matrix exponential symbolically: $e^{At}$

In [3]:
expA = sympy.simplify(sympy.exp(A*t))
expA

⎡⎛   3⋅t    ⎞  -2⋅t  ⎛ 3⋅t    ⎞  -2⋅t⎤
⎢⎝2⋅ℯ    + 1⎠⋅ℯ      ⎝ℯ    - 1⎠⋅ℯ    ⎥
⎢──────────────────  ────────────────⎥
⎢        3                  3        ⎥
⎢                                    ⎥
⎢⎛   3⋅t    ⎞  -2⋅t  ⎛ 3⋅t    ⎞  -2⋅t⎥
⎢⎝2⋅ℯ    - 2⎠⋅ℯ      ⎝ℯ    + 2⎠⋅ℯ    ⎥
⎢──────────────────  ────────────────⎥
⎣        3                  3        ⎦

With this, we can solve the differential equation for arbitary initial conditons $x_0$.

In [4]:
x0_0, x0_1 = sympy.symbols('x^0_0, x^0_1')
x0 = sympy.Matrix([x0_0, x0_1])
expA = sympy.simplify(sympy.exp(A*t))
x_sol = expA*sympy.Matrix([1, 2])
x_sol

⎡  ⎛ 3⋅t    ⎞  -2⋅t   ⎛   3⋅t    ⎞  -2⋅t⎤
⎢2⋅⎝ℯ    - 1⎠⋅ℯ       ⎝2⋅ℯ    + 1⎠⋅ℯ    ⎥
⎢────────────────── + ──────────────────⎥
⎢        3                    3         ⎥
⎢                                       ⎥
⎢  ⎛ 3⋅t    ⎞  -2⋅t   ⎛   3⋅t    ⎞  -2⋅t⎥
⎢2⋅⎝ℯ    + 2⎠⋅ℯ       ⎝2⋅ℯ    - 2⎠⋅ℯ    ⎥
⎢────────────────── + ──────────────────⎥
⎣        3                    3         ⎦

In [5]:
sympy.plot(x_sol[0], (t, 0, 10))
sympy.plot(x_sol[1], (t, 0, 10))

<Figure size 640x480 with 1 Axes>

<Figure size 640x480 with 1 Axes>

## Laplace Transform Method


Recall that:

$\mathcal{L}[e^{at}] = \dfrac{1}{s - a}$

We can also use the Laplace transform to compute the matrix exponential. Notice that:

$\mathcal{L}[e^{At}] = \dfrac{1}{sI - A} = (sI - A)^{-1}$

where $I$ is an identity matrix the same size of $A$, and $A$ is a square matrix.



We can use sympy compute the matrix exponential using this approach.

First compute $(sI - A)$.

In [6]:
s = sympy.symbols('s', complex=True)
s*sympy.eye(2) - A

⎡s    -1  ⎤
⎢         ⎥
⎣-2  s + 1⎦

Now compute the inverse of that expression: $(sI - A)^{-1}$

In [7]:
sympy.Matrix.inv(s*sympy.eye(2) - A)

⎡    2⋅s + 2             2       ⎤
⎢───────────────  ───────────────⎥
⎢2⋅s⋅(s + 1) - 4  2⋅s⋅(s + 1) - 4⎥
⎢                                ⎥
⎢     -2               -s        ⎥
⎢──────────────   ────────────── ⎥
⎣-s⋅(s + 1) + 2   -s⋅(s + 1) + 2 ⎦

Now use the inverse Laplace transform to compute the matrix exponential:

In [8]:
sympy.inverse_laplace_transform(sympy.Matrix.inv(s*sympy.eye(2) - A), s, t)

⎡⎛   3⋅t    ⎞  -2⋅t               ⎛ 3⋅t    ⎞  -2⋅t             ⎤
⎢⎝2⋅ℯ    + 1⎠⋅ℯ    ⋅Heaviside(t)  ⎝ℯ    - 1⎠⋅ℯ    ⋅Heaviside(t)⎥
⎢───────────────────────────────  ─────────────────────────────⎥
⎢               3                               3              ⎥
⎢                                                              ⎥
⎢  ⎛ 3⋅t    ⎞  -2⋅t               ⎛ 3⋅t    ⎞  -2⋅t             ⎥
⎢2⋅⎝ℯ    - 1⎠⋅ℯ    ⋅Heaviside(t)  ⎝ℯ    + 2⎠⋅ℯ    ⋅Heaviside(t)⎥
⎢───────────────────────────────  ─────────────────────────────⎥
⎣               3                               3              ⎦

## Spectral Method 

In [9]:
evects = sympy.Matrix.eigenvects(A)
evects

⎡⎛       ⎡⎡-1/2⎤⎤⎞  ⎛      ⎡⎡1⎤⎤⎞⎤
⎢⎜-2, 1, ⎢⎢    ⎥⎥⎟, ⎜1, 1, ⎢⎢ ⎥⎥⎟⎥
⎣⎝       ⎣⎣ 1  ⎦⎦⎠  ⎝      ⎣⎣1⎦⎦⎠⎦

In [10]:
T = sympy.Matrix.hstack(evects[0][2][0], evects[1][2][0])
T

⎡-1/2  1⎤
⎢       ⎥
⎣ 1    1⎦

In [11]:
T_inv = sympy.simplify(T.inv())
T_inv

⎡-2/3  2/3⎤
⎢         ⎥
⎣2/3   1/3⎦

In [12]:
Lam = sympy.diag(evects[0][0], evects[1][0])
Lam

⎡-2  0⎤
⎢     ⎥
⎣0   1⎦

This process is known as diagonalization, and we can check the decomposition works as expected and we get back A.

In [13]:
sympy.simplify(T*Lam*T_inv)

⎡0  1 ⎤
⎢     ⎥
⎣2  -1⎦

In [14]:
sympy.expand(T*sympy.exp(Lam*t)*T_inv, complex=True).simplify()

⎡⎛   3⋅t    ⎞  -2⋅t  ⎛ 3⋅t    ⎞  -2⋅t⎤
⎢⎝2⋅ℯ    + 1⎠⋅ℯ      ⎝ℯ    - 1⎠⋅ℯ    ⎥
⎢──────────────────  ────────────────⎥
⎢        3                  3        ⎥
⎢                                    ⎥
⎢⎛   3⋅t    ⎞  -2⋅t  ⎛ 3⋅t    ⎞  -2⋅t⎥
⎢⎝2⋅ℯ    - 2⎠⋅ℯ      ⎝ℯ    + 2⎠⋅ℯ    ⎥
⎢──────────────────  ────────────────⎥
⎣        3                  3        ⎦

In [15]:
sympy.simplify(sympy.exp(A*t))

⎡⎛   3⋅t    ⎞  -2⋅t  ⎛ 3⋅t    ⎞  -2⋅t⎤
⎢⎝2⋅ℯ    + 1⎠⋅ℯ      ⎝ℯ    - 1⎠⋅ℯ    ⎥
⎢──────────────────  ────────────────⎥
⎢        3                  3        ⎥
⎢                                    ⎥
⎢⎛   3⋅t    ⎞  -2⋅t  ⎛ 3⋅t    ⎞  -2⋅t⎥
⎢⎝2⋅ℯ    - 2⎠⋅ℯ      ⎝ℯ    + 2⎠⋅ℯ    ⎥
⎢──────────────────  ────────────────⎥
⎣        3                  3        ⎦

# State Space

Now consider the differential equation:
    
$\dot{\vec{x}}(t) = A \vec{x}(t) + B \vec{u}(t)$

The output of the system, $y$ is given as:

$y = Cx + Du$

**Question 1: Use the Laplace Transform of the matrix differential equation to find an expression for x(t).**

**Question 2: Use the Laplace Transform of the matrix differential equation to find an expression for y(t).**

## Numerical Functions

In [16]:
%reset -sf
import control
import numpy as np
from scipy.linalg import expm

In [17]:
A = np.array([[0, -1], [1, 0]])
A

array([[ 0, -1],
       [ 1,  0]])

In [18]:
t = np.linspace(0, 1)
expm(A)

array([[ 0.54030231, -0.84147098],
       [ 0.84147098,  0.54030231]])

In [19]:
expm(A)

array([[ 0.54030231, -0.84147098],
       [ 0.84147098,  0.54030231]])

In [20]:
A = np.array([[0, -5], [1, -2]])
evect = np.linalg.eig(A)

In [21]:
evect[1][1]

array([0.18257419-0.36514837j, 0.18257419+0.36514837j])

In [22]:
evect[0]

array([-1.+2.j, -1.-2.j])

In [23]:
evect[1]

array([[0.91287093+0.j        , 0.91287093-0.j        ],
       [0.18257419-0.36514837j, 0.18257419+0.36514837j]])